<?php
/**
 * GetSendingStats200ResponseStats
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MailOdds
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailOdds\Model;

use \ArrayAccess;
use \MailOdds\ObjectSerializer;

/**
 * GetSendingStats200ResponseStats Class Doc Comment
 *
 * @category Class
 * @package  MailOdds
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetSendingStats200ResponseStats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getSendingStats_200_response_stats';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'period' => 'string',
        'sent' => 'int',
        'delivered' => 'int',
        'bounced' => 'int',
        'deferred' => 'int',
        'failed' => 'int',
        'opened_total' => 'int',
        'opened_unique' => 'int',
        'clicked_total' => 'int',
        'clicked_unique' => 'int',
        'unsubscribed' => 'int',
        'delivery_rate' => 'float',
        'open_rate' => 'float',
        'click_rate' => 'float',
        'bot_opens' => 'int',
        'human_opens' => 'int',
        'bot_open_pct' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'period' => null,
        'sent' => null,
        'delivered' => null,
        'bounced' => null,
        'deferred' => null,
        'failed' => null,
        'opened_total' => null,
        'opened_unique' => null,
        'clicked_total' => null,
        'clicked_unique' => null,
        'unsubscribed' => null,
        'delivery_rate' => null,
        'open_rate' => null,
        'click_rate' => null,
        'bot_opens' => null,
        'human_opens' => null,
        'bot_open_pct' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'period' => false,
        'sent' => false,
        'delivered' => false,
        'bounced' => false,
        'deferred' => false,
        'failed' => false,
        'opened_total' => false,
        'opened_unique' => false,
        'clicked_total' => false,
        'clicked_unique' => false,
        'unsubscribed' => false,
        'delivery_rate' => false,
        'open_rate' => false,
        'click_rate' => false,
        'bot_opens' => false,
        'human_opens' => false,
        'bot_open_pct' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'period' => 'period',
        'sent' => 'sent',
        'delivered' => 'delivered',
        'bounced' => 'bounced',
        'deferred' => 'deferred',
        'failed' => 'failed',
        'opened_total' => 'opened_total',
        'opened_unique' => 'opened_unique',
        'clicked_total' => 'clicked_total',
        'clicked_unique' => 'clicked_unique',
        'unsubscribed' => 'unsubscribed',
        'delivery_rate' => 'delivery_rate',
        'open_rate' => 'open_rate',
        'click_rate' => 'click_rate',
        'bot_opens' => 'bot_opens',
        'human_opens' => 'human_opens',
        'bot_open_pct' => 'bot_open_pct'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'period' => 'setPeriod',
        'sent' => 'setSent',
        'delivered' => 'setDelivered',
        'bounced' => 'setBounced',
        'deferred' => 'setDeferred',
        'failed' => 'setFailed',
        'opened_total' => 'setOpenedTotal',
        'opened_unique' => 'setOpenedUnique',
        'clicked_total' => 'setClickedTotal',
        'clicked_unique' => 'setClickedUnique',
        'unsubscribed' => 'setUnsubscribed',
        'delivery_rate' => 'setDeliveryRate',
        'open_rate' => 'setOpenRate',
        'click_rate' => 'setClickRate',
        'bot_opens' => 'setBotOpens',
        'human_opens' => 'setHumanOpens',
        'bot_open_pct' => 'setBotOpenPct'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'period' => 'getPeriod',
        'sent' => 'getSent',
        'delivered' => 'getDelivered',
        'bounced' => 'getBounced',
        'deferred' => 'getDeferred',
        'failed' => 'getFailed',
        'opened_total' => 'getOpenedTotal',
        'opened_unique' => 'getOpenedUnique',
        'clicked_total' => 'getClickedTotal',
        'clicked_unique' => 'getClickedUnique',
        'unsubscribed' => 'getUnsubscribed',
        'delivery_rate' => 'getDeliveryRate',
        'open_rate' => 'getOpenRate',
        'click_rate' => 'getClickRate',
        'bot_opens' => 'getBotOpens',
        'human_opens' => 'getHumanOpens',
        'bot_open_pct' => 'getBotOpenPct'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('period', $data ?? [], null);
        $this->setIfExists('sent', $data ?? [], null);
        $this->setIfExists('delivered', $data ?? [], null);
        $this->setIfExists('bounced', $data ?? [], null);
        $this->setIfExists('deferred', $data ?? [], null);
        $this->setIfExists('failed', $data ?? [], null);
        $this->setIfExists('opened_total', $data ?? [], null);
        $this->setIfExists('opened_unique', $data ?? [], null);
        $this->setIfExists('clicked_total', $data ?? [], null);
        $this->setIfExists('clicked_unique', $data ?? [], null);
        $this->setIfExists('unsubscribed', $data ?? [], null);
        $this->setIfExists('delivery_rate', $data ?? [], null);
        $this->setIfExists('open_rate', $data ?? [], null);
        $this->setIfExists('click_rate', $data ?? [], null);
        $this->setIfExists('bot_opens', $data ?? [], null);
        $this->setIfExists('human_opens', $data ?? [], null);
        $this->setIfExists('bot_open_pct', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets period
     *
     * @return string|null
     */
    public function getPeriod()
    {
        return $this->container['period'];
    }

    /**
     * Sets period
     *
     * @param string|null $period period
     *
     * @return self
     */
    public function setPeriod($period)
    {
        if (is_null($period)) {
            throw new \InvalidArgumentException('non-nullable period cannot be null');
        }
        $this->container['period'] = $period;

        return $this;
    }

    /**
     * Gets sent
     *
     * @return int|null
     */
    public function getSent()
    {
        return $this->container['sent'];
    }

    /**
     * Sets sent
     *
     * @param int|null $sent sent
     *
     * @return self
     */
    public function setSent($sent)
    {
        if (is_null($sent)) {
            throw new \InvalidArgumentException('non-nullable sent cannot be null');
        }
        $this->container['sent'] = $sent;

        return $this;
    }

    /**
     * Gets delivered
     *
     * @return int|null
     */
    public function getDelivered()
    {
        return $this->container['delivered'];
    }

    /**
     * Sets delivered
     *
     * @param int|null $delivered delivered
     *
     * @return self
     */
    public function setDelivered($delivered)
    {
        if (is_null($delivered)) {
            throw new \InvalidArgumentException('non-nullable delivered cannot be null');
        }
        $this->container['delivered'] = $delivered;

        return $this;
    }

    /**
     * Gets bounced
     *
     * @return int|null
     */
    public function getBounced()
    {
        return $this->container['bounced'];
    }

    /**
     * Sets bounced
     *
     * @param int|null $bounced bounced
     *
     * @return self
     */
    public function setBounced($bounced)
    {
        if (is_null($bounced)) {
            throw new \InvalidArgumentException('non-nullable bounced cannot be null');
        }
        $this->container['bounced'] = $bounced;

        return $this;
    }

    /**
     * Gets deferred
     *
     * @return int|null
     */
    public function getDeferred()
    {
        return $this->container['deferred'];
    }

    /**
     * Sets deferred
     *
     * @param int|null $deferred deferred
     *
     * @return self
     */
    public function setDeferred($deferred)
    {
        if (is_null($deferred)) {
            throw new \InvalidArgumentException('non-nullable deferred cannot be null');
        }
        $this->container['deferred'] = $deferred;

        return $this;
    }

    /**
     * Gets failed
     *
     * @return int|null
     */
    public function getFailed()
    {
        return $this->container['failed'];
    }

    /**
     * Sets failed
     *
     * @param int|null $failed failed
     *
     * @return self
     */
    public function setFailed($failed)
    {
        if (is_null($failed)) {
            throw new \InvalidArgumentException('non-nullable failed cannot be null');
        }
        $this->container['failed'] = $failed;

        return $this;
    }

    /**
     * Gets opened_total
     *
     * @return int|null
     */
    public function getOpenedTotal()
    {
        return $this->container['opened_total'];
    }

    /**
     * Sets opened_total
     *
     * @param int|null $opened_total opened_total
     *
     * @return self
     */
    public function setOpenedTotal($opened_total)
    {
        if (is_null($opened_total)) {
            throw new \InvalidArgumentException('non-nullable opened_total cannot be null');
        }
        $this->container['opened_total'] = $opened_total;

        return $this;
    }

    /**
     * Gets opened_unique
     *
     * @return int|null
     */
    public function getOpenedUnique()
    {
        return $this->container['opened_unique'];
    }

    /**
     * Sets opened_unique
     *
     * @param int|null $opened_unique opened_unique
     *
     * @return self
     */
    public function setOpenedUnique($opened_unique)
    {
        if (is_null($opened_unique)) {
            throw new \InvalidArgumentException('non-nullable opened_unique cannot be null');
        }
        $this->container['opened_unique'] = $opened_unique;

        return $this;
    }

    /**
     * Gets clicked_total
     *
     * @return int|null
     */
    public function getClickedTotal()
    {
        return $this->container['clicked_total'];
    }

    /**
     * Sets clicked_total
     *
     * @param int|null $clicked_total clicked_total
     *
     * @return self
     */
    public function setClickedTotal($clicked_total)
    {
        if (is_null($clicked_total)) {
            throw new \InvalidArgumentException('non-nullable clicked_total cannot be null');
        }
        $this->container['clicked_total'] = $clicked_total;

        return $this;
    }

    /**
     * Gets clicked_unique
     *
     * @return int|null
     */
    public function getClickedUnique()
    {
        return $this->container['clicked_unique'];
    }

    /**
     * Sets clicked_unique
     *
     * @param int|null $clicked_unique clicked_unique
     *
     * @return self
     */
    public function setClickedUnique($clicked_unique)
    {
        if (is_null($clicked_unique)) {
            throw new \InvalidArgumentException('non-nullable clicked_unique cannot be null');
        }
        $this->container['clicked_unique'] = $clicked_unique;

        return $this;
    }

    /**
     * Gets unsubscribed
     *
     * @return int|null
     */
    public function getUnsubscribed()
    {
        return $this->container['unsubscribed'];
    }

    /**
     * Sets unsubscribed
     *
     * @param int|null $unsubscribed unsubscribed
     *
     * @return self
     */
    public function setUnsubscribed($unsubscribed)
    {
        if (is_null($unsubscribed)) {
            throw new \InvalidArgumentException('non-nullable unsubscribed cannot be null');
        }
        $this->container['unsubscribed'] = $unsubscribed;

        return $this;
    }

    /**
     * Gets delivery_rate
     *
     * @return float|null
     */
    public function getDeliveryRate()
    {
        return $this->container['delivery_rate'];
    }

    /**
     * Sets delivery_rate
     *
     * @param float|null $delivery_rate delivery_rate
     *
     * @return self
     */
    public function setDeliveryRate($delivery_rate)
    {
        if (is_null($delivery_rate)) {
            throw new \InvalidArgumentException('non-nullable delivery_rate cannot be null');
        }
        $this->container['delivery_rate'] = $delivery_rate;

        return $this;
    }

    /**
     * Gets open_rate
     *
     * @return float|null
     */
    public function getOpenRate()
    {
        return $this->container['open_rate'];
    }

    /**
     * Sets open_rate
     *
     * @param float|null $open_rate open_rate
     *
     * @return self
     */
    public function setOpenRate($open_rate)
    {
        if (is_null($open_rate)) {
            throw new \InvalidArgumentException('non-nullable open_rate cannot be null');
        }
        $this->container['open_rate'] = $open_rate;

        return $this;
    }

    /**
     * Gets click_rate
     *
     * @return float|null
     */
    public function getClickRate()
    {
        return $this->container['click_rate'];
    }

    /**
     * Sets click_rate
     *
     * @param float|null $click_rate click_rate
     *
     * @return self
     */
    public function setClickRate($click_rate)
    {
        if (is_null($click_rate)) {
            throw new \InvalidArgumentException('non-nullable click_rate cannot be null');
        }
        $this->container['click_rate'] = $click_rate;

        return $this;
    }

    /**
     * Gets bot_opens
     *
     * @return int|null
     */
    public function getBotOpens()
    {
        return $this->container['bot_opens'];
    }

    /**
     * Sets bot_opens
     *
     * @param int|null $bot_opens Opens from known bots/scanners
     *
     * @return self
     */
    public function setBotOpens($bot_opens)
    {
        if (is_null($bot_opens)) {
            throw new \InvalidArgumentException('non-nullable bot_opens cannot be null');
        }
        $this->container['bot_opens'] = $bot_opens;

        return $this;
    }

    /**
     * Gets human_opens
     *
     * @return int|null
     */
    public function getHumanOpens()
    {
        return $this->container['human_opens'];
    }

    /**
     * Sets human_opens
     *
     * @param int|null $human_opens Verified human opens
     *
     * @return self
     */
    public function setHumanOpens($human_opens)
    {
        if (is_null($human_opens)) {
            throw new \InvalidArgumentException('non-nullable human_opens cannot be null');
        }
        $this->container['human_opens'] = $human_opens;

        return $this;
    }

    /**
     * Gets bot_open_pct
     *
     * @return float|null
     */
    public function getBotOpenPct()
    {
        return $this->container['bot_open_pct'];
    }

    /**
     * Sets bot_open_pct
     *
     * @param float|null $bot_open_pct Percentage of opens from bots
     *
     * @return self
     */
    public function setBotOpenPct($bot_open_pct)
    {
        if (is_null($bot_open_pct)) {
            throw new \InvalidArgumentException('non-nullable bot_open_pct cannot be null');
        }
        $this->container['bot_open_pct'] = $bot_open_pct;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


